var dir_90cd76b10e033cac3514a9b88d3aa009 =
[
    [ "addition.cpp", "test_2addition_8cpp.html", "test_2addition_8cpp" ],
    [ "arithmetic.cpp", "test_2arithmetic_8cpp.html", "test_2arithmetic_8cpp" ],
    [ "complex.cpp", "test_2complex_8cpp.html", "test_2complex_8cpp" ],
    [ "convert_expression_to_text.cpp", "convert__expression__to__text_8cpp.html", "convert__expression__to__text_8cpp" ],
    [ "division.cpp", "test_2division_8cpp.html", "test_2division_8cpp" ],
    [ "factorial.cpp", "test_2factorial_8cpp.html", "test_2factorial_8cpp" ],
    [ "function.cpp", "poincare_2test_2function_8cpp.html", "poincare_2test_2function_8cpp" ],
    [ "helper.cpp", "helper_8cpp.html", "helper_8cpp" ],
    [ "helper.h", "helper_8h.html", "helper_8h" ],
    [ "identity.cpp", "identity_8cpp.html", "identity_8cpp" ],
    [ "integer.cpp", "test_2integer_8cpp.html", "test_2integer_8cpp" ],
    [ "logarithm.cpp", "test_2logarithm_8cpp.html", "test_2logarithm_8cpp" ],
    [ "matrix.cpp", "test_2matrix_8cpp.html", "test_2matrix_8cpp" ],
    [ "multiplication.cpp", "test_2multiplication_8cpp.html", "test_2multiplication_8cpp" ],
    [ "parser.cpp", "parser_8cpp.html", "parser_8cpp" ],
    [ "power.cpp", "poincare_2test_2power_8cpp.html", "poincare_2test_2power_8cpp" ],
    [ "properties.cpp", "properties_8cpp.html", "properties_8cpp" ],
    [ "rational.cpp", "test_2rational_8cpp.html", "test_2rational_8cpp" ],
    [ "simplify_mix.cpp", "simplify__mix_8cpp.html", "simplify__mix_8cpp" ],
    [ "store.cpp", "poincare_2test_2store_8cpp.html", "poincare_2test_2store_8cpp" ],
    [ "subtraction.cpp", "test_2subtraction_8cpp.html", "test_2subtraction_8cpp" ],
    [ "symbol.cpp", "test_2symbol_8cpp.html", "test_2symbol_8cpp" ],
    [ "trigo.cpp", "trigo_8cpp.html", "trigo_8cpp" ]
];