var namespace_ion_1_1_u_s_b_1_1_device =
[
    [ "BOSDescriptor", "class_ion_1_1_u_s_b_1_1_device_1_1_b_o_s_descriptor.html", "class_ion_1_1_u_s_b_1_1_device_1_1_b_o_s_descriptor" ],
    [ "Calculator", "class_ion_1_1_u_s_b_1_1_device_1_1_calculator.html", "class_ion_1_1_u_s_b_1_1_device_1_1_calculator" ],
    [ "ConfigurationDescriptor", "class_ion_1_1_u_s_b_1_1_device_1_1_configuration_descriptor.html", "class_ion_1_1_u_s_b_1_1_device_1_1_configuration_descriptor" ],
    [ "Descriptor", "class_ion_1_1_u_s_b_1_1_device_1_1_descriptor.html", "class_ion_1_1_u_s_b_1_1_device_1_1_descriptor" ],
    [ "Device", "class_ion_1_1_u_s_b_1_1_device_1_1_device.html", "class_ion_1_1_u_s_b_1_1_device_1_1_device" ],
    [ "DeviceCapabilityDescriptor", "class_ion_1_1_u_s_b_1_1_device_1_1_device_capability_descriptor.html", "class_ion_1_1_u_s_b_1_1_device_1_1_device_capability_descriptor" ],
    [ "DeviceDescriptor", "class_ion_1_1_u_s_b_1_1_device_1_1_device_descriptor.html", "class_ion_1_1_u_s_b_1_1_device_1_1_device_descriptor" ],
    [ "DFUFunctionalDescriptor", "class_ion_1_1_u_s_b_1_1_device_1_1_d_f_u_functional_descriptor.html", "class_ion_1_1_u_s_b_1_1_device_1_1_d_f_u_functional_descriptor" ],
    [ "DFUInterface", "class_ion_1_1_u_s_b_1_1_device_1_1_d_f_u_interface.html", "class_ion_1_1_u_s_b_1_1_device_1_1_d_f_u_interface" ],
    [ "Endpoint0", "class_ion_1_1_u_s_b_1_1_device_1_1_endpoint0.html", "class_ion_1_1_u_s_b_1_1_device_1_1_endpoint0" ],
    [ "ExtendedCompatIDDescriptor", "class_ion_1_1_u_s_b_1_1_device_1_1_extended_compat_i_d_descriptor.html", "class_ion_1_1_u_s_b_1_1_device_1_1_extended_compat_i_d_descriptor" ],
    [ "Interface", "class_ion_1_1_u_s_b_1_1_device_1_1_interface.html", "class_ion_1_1_u_s_b_1_1_device_1_1_interface" ],
    [ "InterfaceDescriptor", "class_ion_1_1_u_s_b_1_1_device_1_1_interface_descriptor.html", "class_ion_1_1_u_s_b_1_1_device_1_1_interface_descriptor" ],
    [ "LanguageIDStringDescriptor", "class_ion_1_1_u_s_b_1_1_device_1_1_language_i_d_string_descriptor.html", "class_ion_1_1_u_s_b_1_1_device_1_1_language_i_d_string_descriptor" ],
    [ "MicrosoftOSStringDescriptor", "class_ion_1_1_u_s_b_1_1_device_1_1_microsoft_o_s_string_descriptor.html", "class_ion_1_1_u_s_b_1_1_device_1_1_microsoft_o_s_string_descriptor" ],
    [ "PlatformDeviceCapabilityDescriptor", "class_ion_1_1_u_s_b_1_1_device_1_1_platform_device_capability_descriptor.html", "class_ion_1_1_u_s_b_1_1_device_1_1_platform_device_capability_descriptor" ],
    [ "RequestRecipient", "class_ion_1_1_u_s_b_1_1_device_1_1_request_recipient.html", "class_ion_1_1_u_s_b_1_1_device_1_1_request_recipient" ],
    [ "SetupPacket", "class_ion_1_1_u_s_b_1_1_device_1_1_setup_packet.html", "class_ion_1_1_u_s_b_1_1_device_1_1_setup_packet" ],
    [ "Streamable", "class_ion_1_1_u_s_b_1_1_device_1_1_streamable.html", "class_ion_1_1_u_s_b_1_1_device_1_1_streamable" ],
    [ "StringDescriptor", "class_ion_1_1_u_s_b_1_1_device_1_1_string_descriptor.html", "class_ion_1_1_u_s_b_1_1_device_1_1_string_descriptor" ],
    [ "URLDescriptor", "class_ion_1_1_u_s_b_1_1_device_1_1_u_r_l_descriptor.html", "class_ion_1_1_u_s_b_1_1_device_1_1_u_r_l_descriptor" ],
    [ "WebUSBPlatformDescriptor", "class_ion_1_1_u_s_b_1_1_device_1_1_web_u_s_b_platform_descriptor.html", "class_ion_1_1_u_s_b_1_1_device_1_1_web_u_s_b_platform_descriptor" ]
];